### ISSUE TITLE
KeyError: 'empty' in beet when attempting to merge gm4 packs

### ISSUE THREAD

**Issue by adroslice** [Smithed-MC/smithed-python#14]
I just installed the weld CLI to try and merge all my Vanilla Tweaks and Gamemode 4 databacks for ease of distribution, but ran into an issue on the gm4 side of things. I tried renaming a couple of the packs to .zip.skip to see if it was a per-package issue, but the error remains consistently the same. Note that the issue was the same before using the --clear-cache and --dev flags as troubleshooting steps.
Is there something I'm doing wrong, something about the gm4 packs or is this just a bug?
Also, the same issue seems to happen on the website.

Version: v0.19.0

Here's the full debug output:
```
$ weld --clear-cache --log DEBUG --dev *.zip
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│  Weld by Smithed                                                                                                                                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[03:26:30] DEBUG    Using cache: '~\AppData\Roaming\smithed\weld\beet_cache'                                                                                                                             cli.py:83
           INFO     Packs: 'gm4_better_armour_stands_1_21.zip', 'gm4_bookshelf_inspector_1_21.zip', 'gm4_book_binders_1_21.zip', 'gm4_calling_bell_1_21.zip', 'gm4_chairs_1_21.zip',                     cli.py:84
                    'gm4_crossbow_cartridges_1_21.zip', 'gm4_display_frames_1_21.zip', 'gm4_dripleaf_filters_1_21.zip', 'gm4_end_fishing_1_21.zip', 'gm4_holographic_tags_1_21.zip',
                    'gm4_lightning_in_a_bottle_1_21.zip', 'gm4_note_block_interface_1_21.zip', 'gm4_phantom_scarecrows_1_21.zip', 'gm4_pig_tractors_1_21.zip', 'gm4_podzol_rooting_soil_1_21.zip',
                    'gm4_poses_pack_1_21.zip', 'gm4_rope_ladders_1_21.zip', 'gm4_spawner_minecarts_1_21.zip', 'gm4_speed_paths_1_21.zip', 'gm4_sunken_treasure_1_21.zip', 'gm4_xp_storage_1_21.zip',
                    'gm4_ziprails_1_21.zip'
           DEBUG    Run pipeline. (took 0.00s)                                                                                                                                                        utils.py:234
           INFO     gm4_better_armour_stands_1_21.zip                                                                                                                                                  main.py:129
           DEBUG    Run pipeline. (took 0.00s)                                                                                                                                                        utils.py:234
           INFO     gm4_bookshelf_inspector_1_21.zip                                                                                                                                                   main.py:129
           DEBUG    Run pipeline. (took 0.00s)                                                                                                                                                        utils.py:234
           DEBUG    Registering conflict: 'gm4:air'                                                                                                                                                  handler.py:70
           DEBUG    Registering conflict: 'gm4:empty'                                                                                                                                                handler.py:70
           DEBUG    Registering conflict: 'minecraft:blocks/player_head'                                                                                                                             handler.py:70
           DEBUG    Download "https://piston-meta.mojang.com/mc/game/version_manifest_v2.json". (took 0.34s)                                                                                          utils.py:234
[03:26:31] DEBUG    Download "https://piston-meta.mojang.com/v1/packages/306d9b83f6affe635c30347a75cf7fe35f6e064e/1.21.3.json". (took 1.16s)                                                          utils.py:234
[03:26:36] DEBUG    Download "https://piston-data.mojang.com/v1/objects/6f67d19b4467240639cb2c368ffd4b94ba889705/client.jar". (took 5.05s)                                                            utils.py:234
[03:26:38] DEBUG    Extract vanilla pack. (took 1.90s)                                                                                                                                                utils.py:234
           DEBUG    Registering conflict: 'minecraft:empty'                                                                                                                                          handler.py:70
           ERROR    Error: Plugin <beet.toolchain.project.ProjectBuilder object at 0x000001EF542BEFD0> raised an exception.                                                                            utils.py:60

                    Traceback (most recent call last):
                      File "~\AppData\Local\Programs\Python\Python313\Lib\site-packages\beet\toolchain\project.py", line 386, in __call__
                        ctx.data.merge(child_ctx.data)
                        ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
                      File "~\AppData\Local\Programs\Python\Python313\Lib\site-packages\beet\library\base.py", line 1156, in merge
                        super().merge(other)  # type: ignore
                        ~~~~~~~~~~~~~^^^^^^^
                      File "~\AppData\Local\Programs\Python\Python313\Lib\site-packages\beet\core\container.py", line 62, in merge
                        if key not in self or not self.merge(value):  # type: ignore
                                                  ~~~~~~~~~~~~~~~^^^^^^^
                      File "~\AppData\Local\Programs\Python\Python313\Lib\site-packages\beet\library\base.py", line 515, in merge
                        super().merge(other)  # type: ignore
                        ~~~~~~~~~~~~~^^^^^^^
                      File "~\AppData\Local\Programs\Python\Python313\Lib\site-packages\beet\core\container.py", line 62, in merge
                        if key not in self or not self.merge(value):  # type: ignore
                                                  ~~~~~~~~~~~~~~~^^^^^^^
                      File "~\AppData\Local\Programs\Python\Python313\Lib\site-packages\beet\library\base.py", line 397, in merge
                        return pack.merge_policy.merge_with_rules(
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
                            pack=pack,
                            ^^^^^^^^^^
                        ...<5 lines>...
                            ),
                            ^^
                        )
                        ^
                      File "~\AppData\Local\Programs\Python\Python313\Lib\site-packages\beet\library\base.py", line 217, in merge_with_rules
                        if rule(pack, path, current_value, value):
                           ~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                      File "~\AppData\Local\Programs\Python\Python313\Lib\site-packages\smithed\weld\merging\handler.py", line 120, in __call__
                        current.data = self.grab_vanilla(path, json_file_type)
                                       ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
                      File "~\AppData\Local\Programs\Python\Python313\Lib\site-packages\smithed\weld\merging\handler.py", line 173, in grab_vanilla
                        return cast(JsonFile, vanilla.data).data
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
                      File "~\AppData\Local\Programs\Python\Python313\Lib\site-packages\beet\core\container.py", line 198, in __getitem__
                        return self.proxy
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
                      File "~\AppData\Local\Programs\Python\Python313\Lib\site-packages\beet\core\container.py", line 137, in __getitem__
                        value = self.missing(key)
                      File "~\AppData\Local\Programs\Python\Python313\Lib\site-packages\beet\core\container.py", line 176, in missing
                        raise KeyError(key)
                    KeyError: 'empty'


╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ 💥 Failed to weld packs                                                                                                                                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Aborted.
```

**Comment by TheNuclearNexus** [comment]
This has been fixed, there was an issue with custom files in the Minecraft namespace (minecraft:empty loot table was removed in 1.21.4)
